import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import Grid from "@/modules/Grid";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const { t, i18n } = useTranslation("common");
  const currentLanguage = i18n.language;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {t("title")}
          <a href="https://nextjs.org">{t("title-2")}</a>
        </h1>
        <Link href="/" locale={currentLanguage === "en" ? "es" : "en"}>
          <a className={styles.langButton}>{t("lang-button")}</a>
        </Link>

        <p className={styles.description}>
          {t("subtitle")}
          <code className={styles.code}>{t("subtitle-2")}</code>
        </p>
        <Grid />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {t("footer")}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "modules"])),
    },
  };
}
